version: '3.8'

services:
  admin-client:
    build: ./admin-client
    ports:
      - "5173:5173"
    depends_on:
      - admin-server
      - kiosk
  kiosk:
    build: ./kiosk
    ports:
      - "5000:5000"
    depends_on:
      - database
  admin-server:
    build: ./admin-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: facedetection
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jedi2002
    volumes:
      - ./init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
    
  
